name: Test Check

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:

  hello:
    runs-on: ubuntu-latest
    steps:

      - run: |
          sleep 60
          echo "${{github.ref}}"
